@startuml

class Scoreboard
class ScoreboardSet
class ScoreboardGame
class ScoreboardService

class SetPointsPlayer
class SetPointsPlayerGreen
class SetPointsPlayerRed
class GamePointsPlayer
class GamePointsPlayerGreen
class GamePointsPlayerRed

class GameScore
class Score0
class Score15
class Score30
class Score40
class Advantage

class SetScore
class SetScore1
class SetScore7

class Player

Scoreboard *--> "3-5" ScoreboardSet
ScoreboardSet *--> "2" SetPointsPlayer
SetPointsPlayerGreen -up-|> SetPointsPlayer
SetPointsPlayerRed -up-|> SetPointsPlayer

Scoreboard *--> ScoreboardGame
ScoreboardGame o--> "2" GamePointsPlayer
GamePointsPlayerGreen -up-|> GamePointsPlayer
GamePointsPlayerRed -up-|> GamePointsPlayer

GamePointsPlayer o-down-> GameScore
Score0 -up-|> GameScore
Score15 -up-|> GameScore
Score30 -up-|> GameScore
Score40 -up-|> GameScore
Advantage -up-|> GameScore

ScoreboardGame o-down-> "2" GamePointsPlayerOnTieBreak

SetPointsPlayer o-down-> SetScore
SetScore1 -up-|> SetScore
SetScore7 -up-|> SetScore
SetScore1 .left. SetScore7 : from 1 to 7

Scoreboard *--> "2" ScoreboardService
ScoreboardServiceGreen -up-|> ScoreboardService
ScoreboardServiceRed -up-|> ScoreboardService

Player o--> GamePointsPlayer
Player *--> "3-5" SetPointsPlayer
Player *--> ScoreboardService
Player o--> GamePointsPlayerOnTieBreak

@enduml
